[tool.poetry]
name = 'grynn_cli_fplot'
version = '0.2.1'
description = 'cli tool for plotting financial data'
authors = ['Grynn <vishal.doshi@gmail.com>']
license = 'MIT'

[tool.poetry.dependencies]
python = '^3.9'
click = "^8.1.7"
yfinance = "^0.2.44"
matplotlib = "^3.9.2"
dateparser = "^1.2.0"

[tool.poetry.scripts]
fplot = 'grynn_cli_fplot:generate_plot'

[tool.poetry.group.dev.dependencies]
poetry-plugin-export = "^1.8.0"